fix: Handle deadlocks explicitly (#29)
## What kind of change does this PR introduce?

Bug fix

## What is the current behavior?

Since #20 we let errors propagate. We have seen benchmarks fail with:

```
Error: exec SELECT s_i_id, s_quantity, s_data, s_dist_01, s_dist_02, s_dist_03, s_dist_04, s_dist_05, s_dist_06, s_dist_07, s_dist_08, s_dist_09, s_dist_10 FROM stock WHERE (s_w_id, s_i_id) IN ((?,?),(?,?),(?,?),(?,?),(?,?),(?,?),(?,?),(?,?),(?,?),(?,?),(?,?),(?,?),(?,?)) FOR UPDATE failed pq: deadlock detected (40P01)
```

The TPC-C spec does not describe explicitly how to handle such a case
except that a failed transaction must not be considered for throughput
calculation.

## What is the new behavior?

We handle this case explicitly now, rollback the transaction and issue
the next one (instead of retrying this one, we just submit a new one of
the same type).

## Additional context

In order to be able to debug such conditions we added a new `--debug`
flag. We also changed callsites to format errors with `%w` so we can
identify the underlying error.